<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pe1VYp3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pe1VYp3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pe1VYp3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'niveau' => ['privates', '.errored..service_locator.Pe1VYp3.App\\Entity\\Niveau', NULL, 'Cannot autowire service ".service_locator.Pe1VYp3": it needs an instance of "App\\Entity\\Niveau" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'niveau' => 'App\\Entity\\Niveau',
        ]);
    }
}
