<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.03Z6Bcu.App\Entity\Competence' shared service.
     *
     * @return \App\Entity\Competence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.03Z6Bcu": it needs an instance of "App\\Entity\\Competence" but this type has been excluded in "config/services.yaml".');
    }
}
