<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetenceControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.03Z6Bcu.App\Controller\CompetenceController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.03Z6Bcu.App\\Controller\\CompetenceController::edit()'] = ($container->privates['.service_locator.03Z6Bcu'] ?? $container->load('get_ServiceLocator_03Z6BcuService'))->withContext('App\\Controller\\CompetenceController::edit()', $container);
    }
}
