<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MmleznN.App\Controller\FormationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MmleznN.App\\Controller\\FormationController::edit()'] = ($container->privates['.service_locator.MmleznN'] ?? $container->load('get_ServiceLocator_MmleznNService'))->withContext('App\\Controller\\FormationController::edit()', $container);
    }
}
