<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MmleznN.App\Controller\FormationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.MmleznN'] ?? $container->load('get_ServiceLocator_MmleznNService'));

        if (isset($container->privates['.service_locator.MmleznN.App\\Controller\\FormationController::delete()'])) {
            return $container->privates['.service_locator.MmleznN.App\\Controller\\FormationController::delete()'];
        }

        return $container->privates['.service_locator.MmleznN.App\\Controller\\FormationController::delete()'] = $a->withContext('App\\Controller\\FormationController::delete()', $container);
    }
}
