<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNiveauControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kbspjgp.App\Controller\NiveauController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kbspjgp.App\\Controller\\NiveauController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'niveau' => ['privates', '.errored..service_locator.kbspjgp.App\\Entity\\Niveau', NULL, 'Cannot autowire service ".service_locator.kbspjgp": it needs an instance of "App\\Entity\\Niveau" but this type has been excluded in "config/services.yaml".'],
        ], [
            'niveau' => 'App\\Entity\\Niveau',
        ]))->withContext('App\\Controller\\NiveauController::show()', $container);
    }
}
