<?php

namespace ContainerGxcbDn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeilleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.H7F8_fW.App\Entity\Veille' shared service.
     *
     * @return \App\Entity\Veille
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.H7F8_fW": it needs an instance of "App\\Entity\\Veille" but this type has been excluded in "config/services.yaml".');
    }
}
