<?php

namespace ContainerThO7Lfk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNiveauService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WnHvxZc.App\Entity\Niveau' shared service.
     *
     * @return \App\Entity\Niveau
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WnHvxZc": it needs an instance of "App\\Entity\\Niveau" but this type has been excluded in "config/services.yaml".');
    }
}
