<?php

namespace ContainerThO7Lfk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeille2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GG.l7F0.App\Entity\Veille' shared service.
     *
     * @return \App\Entity\Veille
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GG.l7F0": it needs an instance of "App\\Entity\\Veille" but this type has been excluded in "config/services.yaml".');
    }
}
